spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver